application: carbon-14
version: 1
runtime: python
api_version: 1

handlers:

- url: /providers
  script: providers.py
  
- url: /services/upc/widget
  script: services/upc/provider.py

- url: /profile
  script: profile.py
  login: required
  
- url: /.*
  script: main.py
  login: required
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
