application: carbon-14
version: 1
runtime: python
api_version: 1

handlers:

- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: never

- url: /providers
  script: services/providers.py
  
  
- url: /services/upc/static
  static_dir: services/upc/static
  
- url: /services/upc/(.*)
  script: services/upc/provider.py
  
  
- url: /services/rating/static
  static_dir: services/rating/static
  
- url: /services/rating/(.*)
  script: services/rating/provider.py
  
  
- url: /services/environment/static
  static_dir: services/environment/static
  
- url: /services/environment/(.*)
  script: services/environment/provider.py


- url: /.*
  script: main.py
  login: required
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
